### ISSUE TITLE
Replace "observable universe of modules" with plain English

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-9-modules#13]
@eljobe I found the sentence "Explicitly adds the automatic junit module to the **observable universe** of modules." to be a bit pretentious. Dictionary.com seems to define only literal meaning of [observable universe](http://www.dictionary.com/browse/observable-universe). I'm not a native English speaker so feel free to ignore if you disagree.

**Comment by eljobe** [comment]
This one is a little tricky. I picked up that language from the [State of the Module System](http://openjdk.java.net/projects/jigsaw/spec/sotms/) document which seems to use it in a very specific way. At least I should change it to `universe of observable modules` or `set of observable modules` but I am hesitant to try and find a new phrase for `observable module` as I think it is the term the JDK folks are using in their documentation.

I could go with `set of reachable modules` or `set of discoverable modules` or something else. Do you have a preference, @pioterj

**Comment by pioterj** [comment]
@eljobe I don't have a strong opinion about this very minor issue. A "set of observable modules" sounds good to me. It's just "observable universe" togethered that bothered me. "observable" on its own sounds fine, expecially if it's used in JDK documentation.
