### ISSUE TITLE
Formatted text in TOC doesn't change color on hover

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-9-modules#16]
It may not be specific to this guide. @chaficnajjar Could you take care of this one when you have a minute?

<img width="291" alt="screen shot 2017-07-21 at 14 19 19" src="https://user-images.githubusercontent.com/1292566/28463224-b3db1f8a-6e1f-11e7-93f2-6af39f0da97d.png">

**Comment by chaficnajjar** [comment]
Closing as delivered. Thanks for reporting this @pioterj :slightly_smiling_face: 

![screenshot](https://user-images.githubusercontent.com/1498164/29048085-a146b288-7bd7-11e7-86b8-589b7cea3e72.png)
