### ISSUE TITLE
Mention 'chainsaw' plugin, an enhanced 'experimental-jigsaw'

### ISSUE THREAD

**Issue by zyxist** [gradle-guides/building-java-9-modules#22]
Thanks for the guide!

After playing a bit with `experimental-jigsaw`, I discovered that the plugin is unusable in production scenarios, and it seems to be abandoned.

I forked the plugin and started developing a new plugin: https://github.com/zyxist/chainsaw , which picks up the topic. Currently I managed to implement:

 * support for different test engines, including JUnit 4 and JUnit 5,
 * support for additional test modules (e.g. Mockito),
 * module patching,
 * module name verification,
 * annotation processors.

For now, the plugin is able to build projects with JUnit5 tests, Mockito, Dagger, Guava, annotation processors, and deal with `jsr305` issues.

Maybe it would be worth mentioning Chainsaw plugin in the guide, so that people could make more experiments with Jigsaw?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #230](https://github.com/gradle/guides/issues/230) via [**ZenHub**](https://www.zenhub.com/)
