### ISSUE TITLE
Typo in online documentation

### ISSUE THREAD

**Issue by DeeVeX** [gradle-guides/building-java-9-modules#23]
Your migration guide was very detailed and very well explained.

Found a little typo in the last line of the following chapter:
[Step4](https://guides.gradle.org/building-java-9-modules/#step_4_use_the_code_experimental_jigsaw_code_plugin_to_do_the_same_thing)

"Change the line that specifies the module name to use the new **javaMoudle**.name settings."

**Comment by lacasseio** [comment]
Fixed.
