### ISSUE TITLE
script from installDist not working with jigsaw plugin

### ISSUE THREAD

**Issue by sharpTrick** [gradle-guides/building-java-9-modules#24]
Building distribution using style found in 3-applications results in a bin script that can be successfully executed. However 4-plugin does not.

This issue probably belongs in the plugin's repo rather than here. At some point in time I should publish an issue wherever that is as well. However this seemed like a good place for it to be seen by those it will effect.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #231](https://github.com/gradle/guides/issues/231) via [**ZenHub**](https://www.zenhub.com/)
