### ISSUE TITLE
JUnit test configuration could perhaps be simpler

### ISSUE THREAD

**Issue by DJViking** [gradle-guides/building-java-9-modules#29]
The test configuration in the guide does not work for me
https://guides.gradle.org/building-java-9-modules/#modify_the_code_test_code_task_to_consume_the_locally_altered_module

    test {
        inputs.property("moduleName", moduleName)
        doFirst {
            jvmArgs = [
                '--module-path', classpath.asPath, 
                '--add-modules', 'ALL-MODULE-PATH', 
                '--add-reads', "$moduleName=org.junit.jupiter.api", 
                '--patch-module', "$moduleName=" + files(sourceSets.test.java.outputDir).asPath, 
            ]
            classpath = files()
        }
    }

> Task :compileTestJava FAILED
Task ':compileTestJava' is com. up-to-date because:
  Task ':compileTestJava' has additional actions that have changed
All input files are considered out-of-date for incremental task ':compileTestJava'.
Compiling with JDK Java compiler API.
/home/sverre/workspace/movies/src/test/java/com.djviking/movies/MoviesTest.java:3: error: package org.junit.jupiter.api is com. visible
import static org.junit.jupiter.api.Assertions.*;
                               ^
  (package org.junit.jupiter.api is declared in module org.junit.jupiter.api, which is com. in the module graph)
/home/sverre/workspace/movies/src/test/java/com.djviking/movies/MoviesTest.java:5: error: package org.junit.jupiter.api is com. visible
import org.junit.jupiter.api.Test;
                        ^
  (package org.junit.jupiter.api is declared in module org.junit.jupiter.api, which is com. in the module graph)
warning: unkcom.n enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status com. found
/home/sverre/workspace/movies/src/test/java/com.djviking/movies/MoviesTest.java:14: error: cancom. find symbol
        assertEquals(i, j);

However this simpler configuration does work fine:

    test {
        useJUnitPlatform()
        doFirst {
            jvmArgs = [
                '--module-path', classpath.asPath
            ]
        }
    }

Does the Guide need this elaborate test configuration?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #235](https://github.com/gradle/guides/issues/235) via [**ZenHub**](https://www.zenhub.com/)
