### ISSUE TITLE
Application plugin configuration seems unnecessary on Gradle 4.8

### ISSUE THREAD

**Issue by DJViking** [gradle-guides/building-java-9-modules#30]
The application plugin run configuration seems unnecessary. 
https://guides.gradle.org/building-java-9-modules/#modify_the_code_run_code_task_to_use_modules

It works fine without both run{} and startScripts{} configurations running Gradle 4.8 on JDK 10.

Could it be changed from Gradle 4.7 which the Guide was targeted for?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #237](https://github.com/gradle/guides/issues/237) via [**ZenHub**](https://www.zenhub.com/)
