### ISSUE TITLE
Typo and missing link

### ISSUE THREAD

**Issue by sannidhi01** [gradle-guides/building-java-9-modules#34]
In section [Step 2 - Produce Java 9 modules for all subprojects](https://guides.gradle.org/building-java-9-modules/#step_2_produce_java_9_modules_for_all_subprojects), link in information note should:
1. Read as 'Change 5' and not as 'Change 6'
2. Point to apt location.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #268](https://github.com/gradle/guides/issues/268) via [**ZenHub**](https://www.zenhub.com/)
