### ISSUE TITLE
Gradle Distribution Version Needs to be Updated

### ISSUE THREAD

**Issue by thepri10** [gradle-guides/building-java-9-modules#37]
https://github.com/gradle-guides/building-java-9-modules/blob/24a72dc50734db670c6e5227da13ad3f12f71786/src/1-single-module/gradle/wrapper/gradle-wrapper.properties#L1

The Gradle version has to be `4.3` _or above_, otherwise `gradle run` command fails as gradle is not able to resolve `guava` dependency. The same needs to be done for each iteration of the project.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #283](https://github.com/gradle/guides/issues/283) via [**ZenHub**](https://www.zenhub.com/)
