### ISSUE TITLE
Using '--module' for application main corrupts arguments to main()

### ISSUE THREAD

**Issue by dbramel** [gradle-guides/building-java-9-modules#43]
First off, thanks to the contributors here. I'm new to both Gradle and Java modules, and these guides have been a big help.

Now, the issue: when converting an application to use a main class that is in a module via '--module \<module\>/\<mainclass\>' the command line gets screwed up so that some of the arguments intended for the JVM are instead passed to main. You can reproduce it with the examples by having Fairy.java print out the arguments passed into main() in the 3-application version, but just for fun I wrote up the example as a separate project.

Reproducible case: see https://github.com/dbramel/gradle-jvm-module-arg-bug

It's not clear to me if the bug is in this gradle-guide or it's actually a bug in Gradle's java-module support. Gradle's java start scripts are hard-coded so that they use the 'java [options] \<mainClass\> [args]' command-line format. As of java9 there is a different command-line format for modules that contain main classes ('java [options] --module \<module\>/\<mainclass\> [args]') which isn't supported by the start script. By attempting to use --module  with Gradle this guide makes the JVM parse the arguments incorrectly.

The workaround is just to not use the --module format and instead keep specifying the main class in the old, non-module way (i.e. the way it's done in this guide's 2-all-modules version). I'm new to using modules so it's not clear to me if this workaround is usable in all cases.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #297](https://github.com/gradle/guides/issues/297) via [**ZenHub**](https://www.zenhub.com/)
